const fs=require('fs');
let s=fs.readFileSync('index.html','utf8');
if(!fs.existsSync('index.original.html'))fs.copyFileSync('index.html','index.original.html');
const replace=(a,b)=>{if(!s.includes(a))throw Error('No encontrado: '+a.slice(0,100));s=s.replace(a,b);};
replace('<html lang="en">','<html lang="es">');replace('<title>React Artifact</title>','<title>Cráneo y dientes · BodyParts3D</title>');
replace('var l6=46565,YW=', 'var l6=46565,YW=');
const start=s.indexOf('var l6=46565,YW='),end=s.indexOf('function yH()',start);
s=s.slice(0,start)+`var l6=46565,YW=window.BP3D.entries.filter(e=>['skull','maxilla','mandible'].includes(e.type)),F9=window.BP3D.entries.filter(e=>!['skull','maxilla','mandible'].includes(e.type)),lH=[...YW,...F9];\n`+s.slice(end);
replace('[p0,m0]=d0.useState(!0)','[p0,m0]=d0.useState(!1)');replace('[V1,a0]=d0.useState(!1)','[V1,a0]=d0.useState(!0)');
replace('let t0=v0?-0.06:0','let t0=N.current.userData.exploded?-0.06:0');
replace('}},[v0]),d0.useEffect','}},[]),d0.useEffect');
replace('c.removeChild(M.domElement),M.dispose()','c.removeChild(M.domElement),W.current.forEach(mesh=>{mesh.geometry.dispose();mesh.material.dispose()}),W.current.clear(),T.dispose(),M.dispose()');
const ls=s.indexOf('if(!J.current)return;if(!V1)return;');const le=s.indexOf('d0.useEffect(()=>{if(W.current.forEach',ls);
s=s.slice(0,ls)+`if(!J.current||!V1)return; let cancelled=false;
const root=J.current, jaw=N.current, loader=new AH;
W.current.forEach(mesh=>{mesh.removeFromParent();mesh.geometry.dispose();mesh.material.dispose()});W.current.clear();root.position.set(0,0,0);
V0({done:0,total:lH.length,current:'Leyendo OBJ oficiales…'});Z0([]);
(async()=>{let done=0;for(const entry of lH){if(cancelled)return;try{let part=0;for(const file of entry.files){const obj=loader.parse(window.BP3D.models[file]);const meshes=[];obj.traverse(mesh=>{if(mesh.isMesh)meshes.push(mesh)});for(const mesh of meshes){mesh.geometry.rotateX(-Math.PI/2);mesh.geometry.scale(.001,.001,.001);mesh.geometry.computeVertexNormals();mesh.material.dispose();mesh.material=new Pk({color:F9.includes(entry)?w:D,roughness:.65,side:v8,transparent:true});mesh.userData={fmaId:entry.id,entry};(entry.type==='mandible'||entry.jaw==='inf'?jaw:root).add(mesh);W.current.set(entry.id+'-'+part++,mesh);}}}catch(error){Z0(errors=>[...errors,'FMA'+entry.id+': '+error.message]);}done++;V0({done,total:lH.length,current:'FMA'+entry.id});await new Promise(resolve=>setTimeout(resolve,0));}
if(cancelled)return;const box=new T6().setFromObject(root);if(!box.isEmpty()){root.position.sub(box.getCenter(new h));const size=box.getSize(new h),control=$.current,camera=control.object;const distance=Math.max(size.y,size.x/camera.aspect)/ (2*Math.tan(camera.fov*Math.PI/360))*1.3;camera.position.set(0,0,distance);control.target.set(0,0,0);control.update();}V0({done:lH.length,total:lH.length,current:'OBJ oficiales cargados'});
})();return()=>{cancelled=true}},[V1]),`+s.slice(le);
replace('W.current.forEach((c,J0)=>{let P=','W.current.forEach((c,key)=>{let J0=c.userData.fmaId;let P=');
replace('if(k.current){let c=k.current.getObjectByName("grid");if(c)c.visible=F0}','if(N.current)N.current.userData.exploded=v0;if(k.current){let c=k.current.getObjectByName("grid");if(c)c.visible=F0}');
replace('[o0,H,R,F,V,_,l,z,p,n,D,w,Y,b,x,F0,v0]','[o0,H,R,F,V,_,l,z,p,n,D,w,Y,b,x,F0,v0,k0.done]');
replace('let W0=Array.from(W.current.values())','let W0=Array.from(W.current.values()).filter(mesh=>mesh.visible)');
const ustart=s.indexOf('X1=async(c)=>'),uend=s.indexOf(';return C0("div"',ustart);
s=s.slice(0,ustart)+`X1=()=>{a0(false);setTimeout(()=>a0(true),0)}`+s.slice(uend);
replace('" STL"','" estructuras"');replace('children:"Carga STL"','children:"OBJ · fuente oficial"');replace('children:"Cargar modelo remoto (CORS)"','children:"Cargar modelos oficiales"');
replace('children:"Carga desde jsDelivr mirror para evitar CORS del oficial. 29 STL ≈ 15-20MB. El validador offline no carga red."','children:"Mallas originales descargadas de DBArchive LATEST, disponibles localmente."');
replace('children:"Carga local LATEST"','children:"Fuente verificada"');
replace('children:"Descomprime isa_BP3D_4.0_obj_99.zip y arrastra el ZIP aquí. Se filtran por FMA ID de cráneo/dental."','children:"OBJ originales de isa_BP3D_4.0_obj_99.zip. Correspondencia FMA → elementos según isa_element_parts.txt."');
const inputStart=s.indexOf('R0("input",{type:"file",accept:".zip"'),inputEnd=s.indexOf('})',inputStart)+2;
s=s.slice(0,inputStart)+`R0("button",{onClick:X1,className:"w-full py-2 rounded-xl bg-white text-black text-[12px]",children:"Recargar modelos oficiales"})`+s.slice(inputEnd);
replace('Mirror CORS: jsDelivr gh/Kevin-Mattheus-Moerman/BodyParts3D • STLLoader • Coordenadas: mm, Z-up → rot -90° X + scale 0.001 • Centrado por bbox de cráneo','Fuente: DBArchive / BodyParts3D / LATEST. Se conservan las coordenadas relativas originales.');
replace('"https://cdn.jsdelivr.net/gh/Kevin-Mattheus-Moerman/BodyParts3D@master/stl/FMA",L0.id,".stl"','"DBArchive LATEST / isa_BP3D_4.0_obj_99.zip / ",L0.files.join(".obj, "),".obj"');
replace('Array.from(W.current.keys()).slice(0,36)','Array.from(new Set(Array.from(W.current.values(),mesh=>mesh.userData.fmaId)))');
replace('RMB rotar • Scroll zoom • Shift+drag pan','Arrastrar para rotar • Scroll zoom • Botón derecho desplazar');
const fstart=s.indexOf("' Oficial https://dbarchive"),fend=s.indexOf("']})",fstart);
s=s.slice(0,fstart)+JSON.stringify(' OBJ originales del archivo oficial isa_BP3D_4.0_obj_99.zip, seleccionados mediante isa_element_parts.txt e isa_parts_list_e.txt. Sin geometría anatómica generada ni mallas de otros proveedores. Procedencia y hashes en data/provenance.json.')+s.slice(fend+1);
s=s.replace('FMA46565 o subpartes.','elementos oficiales del catálogo.');
s=s.replace('solo cráneo + 28 dientes permanentes • Z-up → Y-up • scale 0.001','cráneo + dentición permanente • mallas originales de DBArchive');
s=s.replace('Objetivo: solo cráneo y dental • target: visor_craneo_dental_bodyparts3d.html • Vista actual: ','Cráneo y dental • Vista actual: ');
// Classic script data also works when index.html is opened directly from disk.
s=s.replace('<body>','<body>\n<script src="data/models.js"></script>');
fs.writeFileSync('index.html',s);
const scripts=[...s.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]);for(const js of scripts)new (require('vm').Script)(js);
console.log('Visor actualizado; JavaScript válido');
